module Calamari
  module Errors
    INVALID_EMPLOYEE_CODE = 'INVALID_EMPLOYEE'.freeze
    INVALID_DATE_FROM_CODE = 'INVALID_DATE_FROM'.freeze
    INVALID_DATE_TO_CODE = 'INVALID_DATE_TO'.freeze
    INVALID_ABSENCE_TYPE_CODE = 'INVALID_ABSENCE_TYPE'.freeze
    INVALID_TEAM_CODE = 'INVALID_TEAM_CODE'.freeze
    INVALID_POSITION_CODE = 'INVALID_POSITION'.freeze
    INVALID_CONTRACT_TYPE_CODE = 'INVALID_CONTRACT_TYPE'.freeze
    INVALID_CREATE_DATE_FROM_CODE = 'INVALID_CREATE_DATE_FROM'.freeze
    INVALID_CREATE_DATE_TO_CODE = 'INVALID_CREATE_DATE_TO'.freeze
    INVALID_CREATE_UPDATE_FROM_CODE = 'INVALID_CREATE_UPDATE_FROM'.freeze
    INVALID_CREATE_UPDATE_TO_CODE = 'INVALID_CREATE_UPDATE_TO'.freeze
  end
end